/*
		A basic implementation of the JFrame class.
*/
package application.ftcontroller;

import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import java.util.*;

import nodesystem.AMessage;
import nodesystem.CommunicationNode;
import controlledparts.ControlledFrame;
import ft.*;
import controlledparts.*;


import controlledparts.ControlledButton;
import javax.swing.JTextField;
import javax.swing.JLabel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
/**
* This code was edited or generated using CloudGarden's Jigloo
* SWT/Swing GUI Builder, which is free for non-commercial
* use. If Jigloo is being used commercially (ie, by a corporation,
* company or business for any purpose whatever) then you
* should purchase a license for each developer using Jigloo.
* Please visit www.cloudgarden.com for details.
* Use of Jigloo implies acceptance of these licensing terms.
* A COMMERCIAL LICENSE HAS NOT BEEN PURCHASED FOR
* THIS MACHINE, SO JIGLOO OR THIS CODE CANNOT BE USED
* LEGALLY FOR ANY CORPORATE OR COMMERCIAL PURPOSE.
*/
public class FtControlWorkerFrame extends ControlledFrame
implements 
FrameWithControlledPane, FrameWithControlledButton, FrameWithControlledTextAreas

{
	public ControlledScrollPane messagesPane = new ControlledScrollPane();
	public ControlledTextArea messages = new ControlledTextArea();
	protected javax.swing.JLabel JLabel1 = new javax.swing.JLabel();
	public ControlledTextArea commandField = new ControlledTextArea();
	javax.swing.JLabel JLabel2 = new javax.swing.JLabel();
	public ControlledButton enterButton = new ControlledButton();
	public ControlledButton quitButton = new ControlledButton();
	private JLabel jLabel1;
	private JTextField portField;
	private ControlledButton showFtControllerButton;
	private ControlledButton hideFtControllerButton;
	private ControlledButton resetButton;
	public ControlledButton clearButton = new ControlledButton();
	public ControlledButton messageClearButton = new ControlledButton();
	private JLabel jLabel4;
	private JLabel currentMaxTimeLabel;
	private JLabel currentMotorOffTerm;
	private JLabel currentMotorOnTerm;
	private JButton paramSetButton;
	private JLabel jLabel5;
	private JTextField maxTimeField;
	private JTextField motorOffTermField;
	private JLabel jLabel3;
	private JLabel jLabel2;
	private JTextField motorOnTermField;
	Vector panes,buttons, texts;
	Frame ftController;
	Interface iface;
	
	private long maxTime=10000;
	private int motorOnTerm=200;
	private int motorOffTerm=200;

	public FtControlWorkerFrame()
	{
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		/*
		//{{INIT_CONTROLS
		getContentPane().setLayout(null);
		setSize(405,305);
		setVisible(false);
		//}}

		//{{INIT_MENUS
		//}}
		*/
		panes=new Vector();
		panes.addElement(this.messagesPane);
		int numberOfPanes=panes.size();
		for(int i=0;i<numberOfPanes;i++){
			ControlledScrollPane p=(ControlledScrollPane)(panes.elementAt(i));
			p.setFrame(this);
			p.setID(i);
		}

		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		getContentPane().setLayout(null);
		this.setSize(519, 524);
		setVisible(false);
		messagesPane.setOpaque(true);
		getContentPane().add(messagesPane);
		messagesPane.setBounds(24,90,468,250);
		messagesPane.getViewport().add(messages);
		messages.setBackground(java.awt.Color.white);
		messages.setForeground(java.awt.Color.black);
		messages.setFont(new Font("SansSerif", Font.PLAIN, 12));
		messages.setBounds(0,0,464,284);
		JLabel1.setText("Distributed System Recorder/FisherTechnik Controller, worker");
		getContentPane().add(JLabel1);
		JLabel1.setBounds(24,12,384,24);
		getContentPane().add(commandField);
		commandField.setBackground(java.awt.Color.white);
		commandField.setForeground(java.awt.Color.black);
		commandField.setFont(new Font("SansSerif", Font.PLAIN, 12));
		commandField.setBounds(108,348,228,36);
		JLabel2.setText("command:");
		getContentPane().add(JLabel2);
		JLabel2.setBounds(24,348,84,36);
		enterButton.setText("enter");
		enterButton.setActionCommand("enter");
		getContentPane().add(enterButton);
		enterButton.setBackground(new java.awt.Color(204,204,204));
		enterButton.setForeground(java.awt.Color.black);
		enterButton.setFont(new Font("Dialog", Font.BOLD, 12));
		enterButton.setBounds(336,348,84,36);
		quitButton.setActionCommand("quit");
		quitButton.setToolTipText("quit, exit");
		getContentPane().add(quitButton);
		quitButton.setBackground(new java.awt.Color(204,204,204));
		quitButton.setForeground(java.awt.Color.black);
		quitButton.setFont(new Font("Dialog", Font.BOLD, 12));
		quitButton.setBounds(290,36,100,24);
		clearButton.setActionCommand("enter");
		clearButton.setToolTipText("clear command area");
		getContentPane().add(clearButton);
		clearButton.setBackground(new java.awt.Color(204,204,204));
		clearButton.setForeground(java.awt.Color.black);
		clearButton.setFont(new Font("Dialog", Font.BOLD, 12));
		clearButton.setBounds(420,348,72,36);
		messageClearButton.setActionCommand("clear");
		messageClearButton.setToolTipText("clear big area");
		getContentPane().add(messageClearButton);
		messageClearButton.setBackground(new java.awt.Color(204,204,204));
		messageClearButton.setForeground(java.awt.Color.black);
		messageClearButton.setFont(new Font("Dialog", Font.BOLD, 12));
		messageClearButton.setBounds(390,36,100,24);
		{
			showFtControllerButton = new ControlledButton();
			this.getContentPane().add(showFtControllerButton);
			showFtControllerButton.setFont(new Font("Dialog", Font.BOLD, 10));
			showFtControllerButton.setText("show FT controller");
			showFtControllerButton.setBounds(20, 36, 130, 24);
		}
		{
			hideFtControllerButton = new ControlledButton();
			this.getContentPane().add(hideFtControllerButton);
			hideFtControllerButton.setFont(new Font("Dialog", Font.BOLD, 10));
			hideFtControllerButton.setText("hide FT controller");
			hideFtControllerButton.setBounds(150, 36, 130, 24);
		}
		{
			resetButton = new ControlledButton();
			this.getContentPane().add(resetButton);
			resetButton.setBounds(336, 386, 84, 30);
			resetButton.setFont(new Font("Dialog", Font.BOLD, 10));
			resetButton.setText("reset");
		}
		{
			portField = new JTextField();
			this.getContentPane().add(portField);
			portField.setBounds(115, 63, 89, 24);
		}
		{
			jLabel1 = new JLabel();
			this.getContentPane().add(jLabel1);
			jLabel1.setText("serial port:");
			jLabel1.setBounds(27, 63, 83, 22);
		}
		{
			motorOnTermField = new JTextField();
			getContentPane().add(motorOnTermField);
			motorOnTermField.setText("200");
			motorOnTermField.setBounds(175, 413, 63, 21);
		}
		{
			jLabel2 = new JLabel();
			getContentPane().add(jLabel2);
			jLabel2.setText("contineous work parameter");
			jLabel2.setBounds(14, 392, 168, 21);
		}
		{
			jLabel3 = new JLabel();
			getContentPane().add(jLabel3);
			jLabel3.setText("motor on term");
			jLabel3.setBounds(63, 413, 105, 21);
		}
		{
			motorOffTermField = new JTextField();
			getContentPane().add(motorOffTermField);
			motorOffTermField.setText("200");
			motorOffTermField.setBounds(175, 434, 63, 21);
		}
		{
			jLabel4 = new JLabel();
			getContentPane().add(jLabel4);
			jLabel4.setText("motor off term");
			jLabel4.setBounds(63, 434, 98, 21);
		}
		{
			maxTimeField = new JTextField();
			getContentPane().add(maxTimeField);
			maxTimeField.setText("10000");
			maxTimeField.setBounds(175, 455, 63, 21);
		}
		{
			jLabel5 = new JLabel();
			getContentPane().add(jLabel5);
			jLabel5.setText("max time");
			jLabel5.setBounds(63, 455, 91, 21);
		}
		{
			paramSetButton = new JButton();
			getContentPane().add(paramSetButton);
			paramSetButton.setText("set");
			paramSetButton.setBounds(175, 392, 63, 21);
			paramSetButton.addActionListener(new ActionListener() {
				public void actionPerformed(ActionEvent evt) {
					paramSetButtonActionPerformed(evt);
				}
			});
		}
		{
			currentMotorOnTerm = new JLabel();
			getContentPane().add(currentMotorOnTerm);
			currentMotorOnTerm.setBounds(238, 413, 56, 21);
		}
		{
			currentMotorOffTerm = new JLabel();
			getContentPane().add(currentMotorOffTerm);
			currentMotorOffTerm.setBounds(238, 434, 42, 21);
		}
		{
			currentMaxTimeLabel = new JLabel();
			getContentPane().add(currentMaxTimeLabel);
			currentMaxTimeLabel.setBounds(238, 455, 63, 21);
		}
		ImageIcon clearIcon=new ImageIcon("images/clear-icon.GIF");
		ImageIcon exitIcon=new ImageIcon("images/exit-icon.GIF");
		messageClearButton.setIcon(clearIcon);
		quitButton.setIcon(exitIcon);
		clearButton.setIcon(clearIcon);
/*
		try {
			exitIcon.setImageLocation(symantec.itools.net.RelativeURL.getURL("images/exit-icon.GIF"));
		}
		catch (java.net.MalformedURLException error) { }
*/		
		buttons=new Vector();
		buttons.addElement( this.enterButton);
		buttons.addElement( this.clearButton);
		buttons.addElement( this.quitButton);
		buttons.addElement( this.messageClearButton);
	    buttons.addElement( this.showFtControllerButton);
	    buttons.addElement( this.hideFtControllerButton);
	    buttons.addElement( this.resetButton);
	
		int numberOfButtons=buttons.size();
	
		for(int i=0;i<numberOfButtons;i++){
			SelectedButton b=(SelectedButton)(buttons.elementAt(i));
			b.setFrame(this);
			b.setID(i);
		}
	
		texts=new Vector();
		texts.addElement(this.messages);
		texts.addElement(this.commandField);
	
		int numberOfTextAreas=texts.size();
		for(int i=0;i<numberOfTextAreas;i++){
			ControlledTextArea t=(ControlledTextArea)(texts.elementAt(i));
			t.setFrame(this);
			t.setID(i);
		}
		this.portField.setEditable(true);
		this.portField.setText("COM2");
		super.registerListeners();

	}

    public boolean isControlledByLocalUser(){
    	return true;
    }

	public boolean isDirectOperation()
    {
    	return true;
    }

	public void receiveEvent(String s)
	{
		// This method is derived from interface Spawnable
		// to do: code goes here
		this.messages.append(s+"\n");
		this.parse(s);
	}

    public ControlledFrame spawnMain(CommunicationNode gui, String args, int pID, String controlMode)
    {
        // This method is derived from interface Spawnable
        // to do: code goes here
//           NetworkTesterWorkerFrame frame=new NetworkTesterWorkerFrame("NetworkTester Worker");
           FtControlWorkerFrame frame=this;
           this.setTitle("FisherTechnik Controller Worker");
           frame.communicationNode=gui;
           frame.pID=pID;
           frame.ebuff=gui.commandTranceiver.ebuff;

           frame.show();
           return frame;
    }
    
	public FtControlWorkerFrame(String sTitle)
	{
		this();
		setTitle(sTitle);
	}

	static public void main(String args[])
	{
		(new FtControlWorkerFrame()).setVisible(true);
	}

	public void addNotify()
	{
		// Record the size of the window prior to calling parents addNotify.
		Dimension size = getSize();

		super.addNotify();

		if (frameSizeAdjusted)
			return;
		frameSizeAdjusted = true;

		// Adjust size of frame according to the insets and menu bar
		Insets insets = getInsets();
		javax.swing.JMenuBar menuBar = getRootPane().getJMenuBar();
		int menuBarHeight = 0;
		if (menuBar != null)
			menuBarHeight = menuBar.getPreferredSize().height;
		setSize(insets.left + insets.right + size.width, insets.top + insets.bottom + size.height + menuBarHeight);
	}

	// Used by addNotify
	boolean frameSizeAdjusted = false;

	//{{DECLARE_CONTROLS
	//}}

	//{{DECLARE_MENUS
	//}}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledPane#changeScrollbarValue(int, int, int)
	 */
	public void changeScrollbarValue(int paneID, int barID, int value) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledPane#hideScrollBar(int, int)
	 */
	public void hideScrollBar(int paneID, int barID) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledPane#scrollBarHidden(int, int)
	 */
	public void scrollBarHidden(int paneID, int barId) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledPane#scrollBarShown(int, int)
	 */
	public void scrollBarShown(int paneID, int barID) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledPane#scrollBarValueChanged(int, int, int)
	 */
	public void scrollBarValueChanged(int paneID, int barID, int v) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledPane#showScrollBar(int, int)
	 */
	public void showScrollBar(int paneID, int barID) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledButton#clickButton(int)
	 */
	public void clickButton(int i) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledButton#focusButton(int)
	 */
	public void focusButton(int i) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledButton#mouseClickedAtButton(int)
	 */
	public void mouseClickedAtButton(int i) {
		// TODO 自動生成されたメソッド・スタブ
		if(i==this.enterButton.getID()){
		//	 buttons.addElement( this.enterButton);
			String command=commandField.getText();
			if(command.equals("")) return;
			int startTime=communicationNode.eventRecorder.timer.getTime();
			String theMessage=""+startTime + "," + command;
			this.messages.append(theMessage+"\n");
			this.messages.setCaretPosition(
				this.messages.getText().length());

			this.communicationNode.eventRecorder.recordMessage(theMessage);
			if(parse(command)){
			}
			else{
				this.messages.append("failed\n");
				this.messages.setCaretPosition(
					this.messages.getText().length());
			}
			clickButton(this.enterButton.getID());
		}
		else
		if(i==this.clearButton.getID()){
		//   buttons.addElement( this.clearButton);
			 this.commandField.setText("");
		}
		else
		if(i==this.quitButton.getID()){
		//   buttons.addElement( this.quitButton);
		//    close();
			 this.parse("quit");
		}
		else
		if(i==this.messageClearButton.getID()){
		// messageClearButton
			 this.messages.setText("");
			 messages.repaint();
		}
		else
		if(i==this.showFtControllerButton.getID()){
			String comport=this.portField.getText();
			if(ftController!=null){
				ftController.show(true);
				return;
			}
			if(iface==null){
				try {
				  iface = Interface.open(comport);
				} catch (Exception e) 
				{ iface=null; }
			}
            if(iface!=null){
				  this.ftController = new Frame("Ft Controller ["+comport+"]");
				  ftController.add(new Diagnose(iface), BorderLayout.CENTER);
				  ftController.addWindowListener(new WindowAdapter() {
					public void windowClosing (WindowEvent e) { System.exit(0); }
				  });
				  ftController.pack(); ftController.show();

				  new Thread(iface).start();
            }
		}
		else
		if(i==this.hideFtControllerButton.getID()){
			ftController.show(false);
		}
		else
		if(i==this.resetButton.getID()){
			this.reset();
		}

	}
	public void waitTime(int millisec)
	{
		try{
			Thread.sleep((long)millisec);
		}
		catch(InterruptedException e){
		}
	}

	public void reset(){
		this.setMotor("1","0");
		this.waitTime(50);
		this.setMotor("2","0");
		this.waitTime(50);
		this.setMotor("3","0");
		this.waitTime(50);
		this.setMotor("4","0");
		this.waitTime(50);
		this.setCount("1","0","1");
		this.waitTime(50);
		this.setCount("2","0","1");
		this.waitTime(50);
		this.setCount("3","0","1");
		this.waitTime(50);
		this.setCount("4","0","1");
		this.waitTime(50);
		this.setCount("5","0","1");
		this.waitTime(50);
		this.setCount("6","0","1");
		this.waitTime(50);
		this.setCount("7","0","1");
		this.waitTime(50);
		this.setCount("8","0","1");
		this.waitTime(50);
		this.mouseClickedAtButton(this.clearButton.getID());
		this.waitTime(50);
		this.mouseClickedAtButton(this.messageClearButton.getID());
	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledButton#mouseEnteredAtButton(int)
	 */
	public void mouseEnteredAtButton(int i) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledButton#mouseExitedAtButton(int)
	 */
	public void mouseExitedAtButton(int i) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledButton#unfocusButton(int)
	 */
	public void unfocusButton(int i) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledTextAreas#clickMouseOnTheText(int, int, int, int)
	 */
	public void clickMouseOnTheText(int i, int p, int x, int y) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledTextAreas#dragMouseOnTheText(int, int, int, int)
	 */
	public void dragMouseOnTheText(int id, int position, int x, int y) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledTextAreas#enterMouseOnTheText(int, int, int)
	 */
	public void enterMouseOnTheText(int id, int x, int y) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledTextAreas#exitMouseOnTheText(int, int, int)
	 */
	public void exitMouseOnTheText(int id, int x, int y) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledTextAreas#keyIsPressedAtATextArea(int, int, int)
	 */
	public void keyIsPressedAtATextArea(int i, int p, int key) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledTextAreas#keyIsReleasedAtTextArea(int, int, int)
	 */
	public void keyIsReleasedAtTextArea(int id, int p, int key) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledTextAreas#keyIsTypedAtATextArea(int, int, int)
	 */
	public void keyIsTypedAtATextArea(int i, int p, int key) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledTextAreas#mouseClickedAtTextArea(int, int, int, int)
	 */
	public void mouseClickedAtTextArea(int i, int p, int x, int y) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledTextAreas#mouseDraggedAtTextArea(int, int, int, int)
	 */
	public void mouseDraggedAtTextArea(int id, int position, int x, int y) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledTextAreas#mouseEnteredAtTheText(int, int, int)
	 */
	public void mouseEnteredAtTheText(int id, int x, int y) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledTextAreas#mouseExitAtTheText(int, int, int)
	 */
	public void mouseExitAtTheText(int id, int x, int y) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledTextAreas#mouseMoveAtTextArea(int, int, int)
	 */
	public void mouseMoveAtTextArea(int id, int x, int y) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledTextAreas#mousePressedAtTextArea(int, int, int, int)
	 */
	public void mousePressedAtTextArea(int i, int p, int x, int y) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledTextAreas#mouseReleasedAtTextArea(int, int, int, int)
	 */
	public void mouseReleasedAtTextArea(int id, int position, int x, int y) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledTextAreas#moveMouseOnTheText(int, int, int)
	 */
	public void moveMouseOnTheText(int id, int x, int y) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledTextAreas#pressKey(int, int, int)
	 */
	public void pressKey(int i, int p, int code) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledTextAreas#pressMouseOnTheText(int, int, int, int)
	 */
	public void pressMouseOnTheText(int i, int p, int x, int y) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledTextAreas#releaseKey(int, int, int)
	 */
	public void releaseKey(int i, int p, int code) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledTextAreas#releaseMouseOnTheText(int, int, int, int)
	 */
	public void releaseMouseOnTheText(int id, int position, int x, int y) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledTextAreas#setTextOnTheText(int, int, java.lang.String)
	 */
	public void setTextOnTheText(int i, int pos, String s) {
		// TODO 自動生成されたメソッド・スタブ

	}

	/* (非 Javadoc)
	 * @see controlledparts.FrameWithControlledTextAreas#typeKey(int, int, int)
	 */
	public void typeKey(int i, int p, int key) {
		// TODO 自動生成されたメソッド・スタブ

	}
	
	/**
	* Auto-generated method for setting the popup menu for a component
	*/
	private void setComponentPopupMenu(
		final java.awt.Component parent,
		final javax.swing.JPopupMenu menu) {
		parent.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent e) {
				if (e.isPopupTrigger())
					menu.show(parent, e.getX(), e.getY());
			}
			public void mouseReleased(java.awt.event.MouseEvent e) {
				if (e.isPopupTrigger())
					menu.show(parent, e.getX(), e.getY());
			}
		});
	}
	
	int testID;
	String masterNode;

	public void setTestID(int id)
	{
		testID=id;
	}

	public synchronized boolean parse(String command)
	{
		/*
		command:
		  enter ... meta
		  clear ... meta
		  quit  ... meta
		  set <command> ... meta
		  connect <server-address>
		  sendreceive <datasize>
		  sendreceive-n <datasize> <times>
		  send <datasize>
		  receive
		  load <file-name>
		  testid <id>
		  returnnodeinfo <return-address>        
		  
		  set-motor <Motor ID> <current>
		         <Motor ID> = 1|...|4
		         <current>  = -1 | 0 | 1
		  get-digital <Digital Sensor ID>
		         <Digital Sensor ID> = 1|...|8
		  get-analog <Analog Sensor ID>
		         <Analog Sensor ID> = 1|2
		         
		  set-motor-until-on <Motor ID> <current> <Digital Sensor ID>
		  set-motor-until-off <Motor ID> <current> <Digital Sensor ID>
		  
		  set-motor-while-count-lt <Motor ID> <current> <Digital Sensor ID> <count>
		  set-motor-while-count-le <Motor ID> <current> <Digital Sensor ID> <count>
		  set-motor-while-count-gt <motor ID> <current> <Digital Sensor ID> <count>
		  set-motor-while-count-ge <motor ID> <current> <Ditigal sensor ID> <count>
		  set-counter <Digital Sensor ID> <count>
		  set-maxtime <time>
		  stop
		  
		*/
		if(command.indexOf("stop")==0){
			for(int i=0;i<4;i++){
				setMotor(""+i,""+0);
			}
		}
		if(command.indexOf("enter")==0){
			this.clickButton(this.enterButton.getID());
//			  String x=s.substring("chat ".length());
			return true;
		}
		else
		if(command.indexOf("clear")==0){
			this.clickButton(this.clearButton.getID());
			return true;
		}
		else
		if(command.indexOf("clearmessage")==0){
			this.clickButton(this.messageClearButton.getID());
			return true;
		}
		else
		if(command.indexOf("quit")==0){
//			  this.clickButton(2);
			this.exitThis();
			return true;
		}
		else
		if(command.indexOf("set ")==0){
			String x=command.substring("set ".length());
			// set <command>
			this.commandField.setText(x);
			return true;
		}
		else
		if(command.indexOf("testid ")==0){
			String x=command.substring("testid ".length());
			// setTestID <testID>       
			setTestID((new Integer(x)).intValue());
			return true;
		}
		else
		if(command.indexOf("getnodeinfo ")==0){
			// getnodeinfo <return node id>       
			masterNode=command.substring("getnodeinfo ".length());
			String myaddress=this.communicationNode.getMyAddress();
			int slashPlace=myaddress.indexOf("/");
			String theAddress="";
			if(slashPlace>=1){
    			StringTokenizer st=new StringTokenizer(myaddress,"/");
	    		String dmy=st.nextToken();
		    	theAddress=st.nextToken();
			}
			else{
				theAddress=myaddress;
			}
			this.sendEvent("node "+masterNode, 
			 masterCommand, "nodeinfo "+this.communicationNode.serialNo+" "+theAddress);
			messages.append("return nodeinfo "+this.communicationNode.serialNo+" "+theAddress+ " to the node "+masterNode+"\n");
			return true;
		}
		else
		if(command.indexOf("returninfo ")==0){
			// returninfo <return node id>       
			String theNode=command.substring("returninfo ".length());
			String myaddress=this.communicationNode.getMyAddress();
			int slashPlace=myaddress.indexOf("/");
			String theAddress="";
			if(slashPlace>=1){
    			StringTokenizer st=new StringTokenizer(myaddress,"/");
	    		String dmy=st.nextToken();
		    	theAddress=st.nextToken();
			}
			else{
				theAddress=myaddress;
			}
		this.sendEvent("node "+theNode, 
			 masterCommand, "nodeinfo "+this.communicationNode.serialNo+" "+theAddress);
			messages.append("return nodeinfo "+this.communicationNode.serialNo+" "+theAddress+ " to the node "+theNode+"\n");
			return true;
		}
		else
		if(command.indexOf("send ")==0){
			String x=command.substring("send ".length());
			// send <data-size>            
			return true;
		}
		else
/*		
		set-motor <Motor ID> <current>
			   <Motor ID> = 1|...|4
			   <current>  = 0(off) | 1(left) | 2(right)
		get-digital <Digital Sensor ID> <return node ID>
	    get-count <Ditigal Sensor ID> <return node ID>
	    set-count <Ditital Sensor ID> <value>
			   <Digital Sensor ID> = 1|...|8
		get-analog <Analog Sensor ID> <return node ID>
			   <Analog Sensor ID> = 1|2
*/				
		if(command.indexOf("set-motor ")==0){
			StringTokenizer st=new StringTokenizer(command.substring("set-motor ".length()));
			String motorId=st.nextToken();
			String current=st.nextToken();
			setMotor(motorId,current);
			return true;
		}
		else
		if(command.indexOf("set-count ")==0){
			StringTokenizer st=new StringTokenizer(command.substring("set-count ".length()));
			String digitalId=st.nextToken();
			String value=st.nextToken();
			if(st.hasMoreTokens()) {
			  String delta=st.nextToken();
			  setCount(digitalId,value,delta);
			}
			else{
				setCount(digitalId,value,"1");
			}
			return true;
		}
		else
		if(command.indexOf("get-digital ")==0){
			StringTokenizer st=new StringTokenizer(command.substring("get-digital ".length()));
			String digitalId=st.nextToken();
			int x=getDigital(digitalId);
			if(st.hasMoreTokens()) {
			  String returnId=st.nextToken();
			  this.sendEvent("node "+returnId, masterCommand, 
                  "resultofnode "+this.communicationNode.serialNo+" "+x);
			  messages.append("return "+x+" for get-digital from the node "+returnId+"\n");
			}
			else{
				messages.append("return "+x+" for get-digital \n");				
			}
			return true;
		}
		else
		if(command.indexOf("get-count ")==0){
			StringTokenizer st=new StringTokenizer(command.substring("get-count ".length()));
			String digitalId=st.nextToken();
			int x=getCount(digitalId);
			if(st.hasMoreTokens()) {
			  String returnId=st.nextToken();
			  this.sendEvent("node "+returnId, masterCommand, 
                 "resultofnode "+this.communicationNode.serialNo+" "+x);
			  messages.append("return "+x+" for get-count from the node "+returnId+"\n");
			}
			else{
				messages.append("return "+x+" for get-count \n");				
			}
			return true;
		}
		else
		if(command.indexOf("get-analog ")==0){
			StringTokenizer st=new StringTokenizer(command.substring("get-analog ".length()));
			String analogId=st.nextToken();
			float x=getDigital(analogId);
			if(st.hasMoreTokens()) {
			  String returnId=st.nextToken();
			  this.sendEvent("node "+returnId, masterCommand, 
                 "resultofnode "+this.communicationNode.serialNo+" "+x);
			  messages.append("return "+x+" for get-analog from the node "+returnId+"\n");
			}
			else{
				messages.append("return "+x+" for get-digital \n");				
			}
			return true;
		}
		else
		if(command.indexOf("reset")==0){
			this.reset();
			return true;
		}
		else
			/*
			  set-maxtime <time>
			  set-motor-until-digital "on"|"off" <Motor ID> <current> <Digital Sensor ID>
			  
			  set-motor-while-count "lt"|"le"|"gt"|ge <Motor ID> <current> <Digital Sensor ID> <count>

			*/
		if(command.indexOf("set-motor-until-digital ")==0){
			StringTokenizer st=new StringTokenizer(command.substring("set-motor-until-tigial ".length()));
			String onoff=st.nextToken(); if(onoff==null) return false;
			String motorId=st.nextToken(); if(motorId==null) return false;
			String current=st.nextToken(); if(current==null) return false;
			String did=st.nextToken(); if(did==null) return false;
			int x=getDigital(did);
			long startTime=System.currentTimeMillis();
			if(onoff.equals("on")){
				if(x==1) {
					setMotor(motorId,"0");
					return true;
				}
					
			}
			else{
				if(x==0) {
					setMotor(motorId,"0");
					return true;
				}
				
			}
			setMotor(motorId,current);			
			while(true){
				try{
					Thread.sleep(this.motorOnTerm);
				}
				catch(InterruptedException e){}
				setMotor(motorId,"0");
				long now=System.currentTimeMillis();
				if(startTime+this.maxTime<=now){
					return true;
				}
				try{
					Thread.sleep(this.motorOffTerm);
				}
				catch(InterruptedException e){}
				x=getDigital(did);
				if(onoff.equals("on")){
					if(x==1) {
//						setMotor(motorId,"0");
						return true;
					}
				}
				else{
					if(x==0) {
//						setMotor(motorId,"0");
						return true;
					}
					
				}
				setMotor(motorId,current);
			}
		}
		else
		if(command.indexOf("set-maxtime ")==0){
			StringTokenizer st=new StringTokenizer(command.substring("set-maxtime ".length()));
			String times=st.nextToken();
			long time=(new Integer(times)).intValue();
			this.maxTime=time;
			return true;
		}
		else
			/*
			  set-motor-until-digital "on"|"off" <Motor ID> <current> <Digital Sensor ID>
			  
			  set-motor-while-count "lt"|"le"|"gt"|ge <Motor ID> <current> <Digital Sensor ID> <count>

			*/
	    if(command.indexOf("set-motor-while-count ")==0){
			StringTokenizer st=new StringTokenizer(command.substring("set-motor-while-count ".length()));
			String rlop=st.nextToken(); if(rlop==null)return false;
			String motorId=st.nextToken(); if(motorId==null) return false;
			String current=st.nextToken(); if(current==null) return false;
			String did=st.nextToken(); if(did==null) return false;
			String count=st.nextToken(); if(count==null) return false;
			long startTime=System.currentTimeMillis();
			setMotor(motorId,current);
			int ct=(new Integer(count)).intValue();
			while(true){
				try{
					Thread.sleep(this.motorOnTerm);
				}
				catch(InterruptedException e){}
				setMotor(motorId,"0");
				long now=System.currentTimeMillis();
				if(startTime+this.maxTime<=now){
					return true;
				}
				try{
					Thread.sleep(this.motorOffTerm);
				}
				catch(InterruptedException e){}
				int x=getCount(did);
				if(rlop.equals("lt")){
					if(!(x<ct)) {
//						setMotor(motorId,"0");
						return true;
					}
				}
				else
				if(rlop.equals("le")){
					if(!(x<=ct)){ 
//						setMotor(motorId,"0");
						return true;
					}
				}
				else
				if(rlop.equals("gt")){
					if(!(x>ct)){ 
//						setMotor(motorId,"0");
						return true;
					}
				}
				else
				if(rlop.equals("ge")){
					if(!(x>=ct)) {
//						setMotor(motorId,"0");
						return true;
					}
				}
				setMotor(motorId,current);
			}
	    	
	    }
	    else
		return false;
	}
	
	void setMotor(String motorId, String current){
		int m=0;
		int c=0;
		try{
    		m=(new Integer(motorId)).intValue();
	    	c=(new Integer(current)).intValue();
		}
		catch(Exception e){
			messages.append("format error:"+motorId+" "+current+"\n");
		}
		iface.set((int)(0x03<<((m-1)*2)),c);
	}
	
	void setCount(String digitalId, String value, String delta){
		int s=0;
		int v=0;
		int d=0;
		try{
			s=(new Integer(digitalId)).intValue();
			v=(new Integer(value)).intValue();
			d=(new Integer(delta)).intValue();
		}
		catch(Exception e){
			messages.append("format error:"+digitalId+" "+value+" "+delta+"\n");
		}
		iface.set((int)(0x01<<(s-1)),v,d);
	}
	
	int getDigital(String digitalId){
		int i=0;
		try{
		    i=(new Integer(digitalId)).intValue();
		}
		catch(Exception e){
			messages.append("format error:"+digitalId+"\n");
		}
		boolean rtn=iface.isSet(0x01<<(i-1));
		if(rtn) return 1; else return 0;
	}
	
	int getCount(String digitalId){
		int i=0;
		try{
			i=(new Integer(digitalId)).intValue();
		}
		catch(Exception e){
			messages.append("format error:"+digitalId+"\n");
		}
		int rtn=iface.isAt(0x01<<(i-1));
		return rtn;
	}
	
	float getAnalog(String analogId){
		int i=0;
		try{
			i=(new Integer(analogId)).intValue();
		}
		catch(Exception e){
			messages.append("format error:"+analogId+"\n");
		}
		float[] rtn=iface.getScale(i<<(i-1));
		return rtn[0];
	}
	
	String masterCommand="ftcontrolmaster";
	
	String commandName="ftcontrolworker";
	public String getCommandName(){
		return commandName;
	}
	
	public void sendEvent(String transmitMode, String command, String subcommand)
	{
		if(ebuff!=null){
			String sending=transmitMode+" "+command+" "
			 +subcommand+this.communicationNode.commandTranceiver.endOfACommand;
			AMessage m=new AMessage();
			m.setHead(sending);
    		this.ebuff.putS(m);
		}
	}
	
	private void paramSetButtonActionPerformed(ActionEvent evt) {
//		System.out.println("paramSetButton.actionPerformed, event=" + evt);
		//TODO add your code for paramSetButton.actionPerformed
		this.maxTime=(new Integer(this.maxTimeField.getText())).longValue();
		this.motorOnTerm=(new Integer(this.motorOnTermField.getText())).intValue();
		this.motorOffTerm=(new Integer(this.motorOffTermField.getText())).intValue();
		this.currentMotorOnTerm.setText(""+motorOnTerm);
		this.currentMotorOffTerm.setText(""+motorOffTerm);
		this.currentMaxTimeLabel.setText(""+maxTime);
	}

}
