package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTAddNode.java */

public class ASTAddNode extends SimpleNode {
	public ASTAddNode(int id) {
		super(id);
	}

	public ASTAddNode(IntVParser p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(IntVParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
