package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTArray.java */

public class ASTArray extends SimpleNode {
	public ASTArray(int id) {
		super(id);
	}

	public ASTArray(IntVParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(IntVParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
