package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTAssignStats.java */

public class ASTAssignStats extends SimpleNode {
	public ASTAssignStats(int id) {
		super(id);
	}

	public ASTAssignStats(IntVParser p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(IntVParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
