package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTCeil.java */

public class ASTCeil extends SimpleNode {
	public ASTCeil(int id) {
		super(id);
	}

	public ASTCeil(IntVParser p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(IntVParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
