package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTDoWhileStat.java */

public class ASTDoWhileStat extends SimpleNode {
	public ASTDoWhileStat(int id) {
		super(id);
	}

	public ASTDoWhileStat(IntVParser p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(IntVParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
