package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTDivNode.java */

public class ASTDivNode extends SimpleNode {
	public ASTDivNode(int id) {
		super(id);
	}

	public ASTDivNode(IntVParser p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(IntVParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
