package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTElseIfStat.java */

public class ASTElseIfStat extends SimpleNode {
	public ASTElseIfStat(int id) {
		super(id);
	}

	public ASTElseIfStat(IntVParser p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(IntVParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
