package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTEQNode.java */

public class ASTEQNode extends SimpleNode {
	public ASTEQNode(int id) {
		super(id);
	}

	public ASTEQNode(IntVParser p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(IntVParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
