package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTExtract.java */

public class ASTExtract extends SimpleNode {
  public ASTExtract(int id) {
    super(id);
  }

  public ASTExtract(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
