package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTFile_getstr.java */

public class ASTFile_getstr extends SimpleNode {
  public ASTFile_getstr(int id) {
    super(id);
  }

  public ASTFile_getstr(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
