package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTForStat.java */

public class ASTForStat extends SimpleNode {
	public ASTForStat(int id) {
		super(id);
	}

	public ASTForStat(IntVParser p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(IntVParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
