package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTFile_delete.java */

public class ASTFile_remove extends SimpleNode {
  public ASTFile_remove(int id) {
    super(id);
  }

  public ASTFile_remove(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
