package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTFile_flush.java */

public class ASTFile_flush extends SimpleNode {
  public ASTFile_flush(int id) {
    super(id);
  }

  public ASTFile_flush(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
