package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTgFillBox.java */

public class ASTgFillBox extends SimpleNode {
  public ASTgFillBox(int id) {
    super(id);
  }

  public ASTgFillBox(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
