package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTGetStat.java */

public class ASTGetStat extends SimpleNode {
	public ASTGetStat(int id) {
		super(id);
	}

	public ASTGetStat(IntVParser p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(IntVParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
