package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTgWindowClose.java */

public class ASTgWindowClose extends SimpleNode {
  public ASTgWindowClose(int id) {
    super(id);
  }

  public ASTgWindowClose(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
