package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTgWindowOpen.java */

public class ASTgWindowOpen extends SimpleNode {
  public ASTgWindowOpen(int id) {
    super(id);
  }

  public ASTgWindowOpen(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
