package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTgFillOval.java */

public class ASTgFillOval extends SimpleNode {
  public ASTgFillOval(int id) {
    super(id);
  }

  public ASTgFillOval(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
