package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTgDrawOval.java */

public class ASTgDrawOval extends SimpleNode {
  public ASTgDrawOval(int id) {
    super(id);
  }

  public ASTgDrawOval(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
