package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTgFillPoint.java */

public class ASTgFillPoint extends SimpleNode {
  public ASTgFillPoint(int id) {
    super(id);
  }

  public ASTgFillPoint(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
