package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTIntVUnit.java */

public class ASTIntVUnit extends SimpleNode {
	public ASTIntVUnit(int id) {
		super(id);
	}

	public ASTIntVUnit(IntVParser p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(IntVParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
