package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTIdent.java */

public class ASTIdent extends SimpleNode {
	public ASTIdent(int id) {
		super(id);
	}

	public ASTIdent(IntVParser p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(IntVParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

/** customizing codes **/
	public String varName;
	public String varName2;
	public boolean flag = true;

}
