package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTLSNode.java */

public class ASTLSNode extends SimpleNode {
	public ASTLSNode(int id) {
		super(id);
	}

	public ASTLSNode(IntVParser p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(IntVParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
