package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTMinNode.java */

public class ASTMinNode extends SimpleNode {
	public ASTMinNode(int id) {
		super(id);
	}

	public ASTMinNode(IntVParser p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(IntVParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
