package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTNOTNode.java */

public class ASTNOTNode extends SimpleNode {
	public ASTNOTNode(int id) {
		super(id);
	}

	public ASTNOTNode(IntVParser p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(IntVParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
