package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTORNode.java */

public class ASTORNode extends SimpleNode {
	public ASTORNode(int id) {
		super(id);
	}

	public ASTORNode(IntVParser p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(IntVParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
