package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTStrlit.java */

public class ASTStrlit extends SimpleNode {
	public ASTStrlit(int id) {
		super(id);
	}

	public ASTStrlit(IntVParser p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(IntVParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

/** customizing codes **/
	public String litString;
}
