package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTStringDecl.java */

public class ASTStringDeclX extends SimpleNode {
  public ASTStringDeclX(int id) {
    super(id);
  }

  public ASTStringDeclX(IntVParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IntVParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

/** customizing codes **/
  public String varName;

}
