package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTSubNode.java */

public class ASTSubNode extends SimpleNode {
	public ASTSubNode(int id) {
		super(id);
	}

	public ASTSubNode(IntVParser p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(IntVParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
