package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTVarDecl.java */

public class ASTVarDecl extends SimpleNode {
	public ASTVarDecl(int id) {
		super(id);
	}

	public ASTVarDecl(IntVParser p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(IntVParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	/** customizing codes **/
	public int decl;
}
