package application.pen;
/* Generated By:JJTree: Do not edit this line. ASTWhileStat.java */

public class ASTWhileStat extends SimpleNode {
	public ASTWhileStat(int id) {
		super(id);
	}

	public ASTWhileStat(IntVParser p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(IntVParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
