package application.pen;
/* Generated By:JJTree: Do not edit this line. IntVParserTreeConstants.java */

public interface IntVParserTreeConstants
{
  public int JJTINTVUNIT = 0;
  public int JJTERROROCCUR = 1;
  public int JJTFUNCTION = 2;
  public int JJTBLOCK = 3;
  public int JJTFUNCTIONVAR = 4;
  public int JJTVARDECL = 5;
  public int JJTDECL = 6;
  public int JJTARRAY = 7;
  public int JJTVOID = 8;
  public int JJTASSIGNSTATS = 9;
  public int JJTASSIGNSTAT = 10;
  public int JJTIFSTAT = 11;
  public int JJTWHILESTAT = 12;
  public int JJTREPEATUNTIL = 13;
  public int JJTFORSTAT = 14;
  public int JJTFORSTATADD = 15;
  public int JJTGETSTAT = 16;
  public int JJTPUTSTAT = 17;
  public int JJTORNODE = 18;
  public int JJTANDNODE = 19;
  public int JJTNOTNODE = 20;
  public int JJTEQNODE = 21;
  public int JJTNTNODE = 22;
  public int JJTLSNODE = 23;
  public int JJTGTNODE = 24;
  public int JJTLENODE = 25;
  public int JJTGENODE = 26;
  public int JJTADDNODE = 27;
  public int JJTSUBNODE = 28;
  public int JJTMULNODE = 29;
  public int JJTDIVNODE = 30;
  public int JJTSURNODE = 31;
  public int JJTMINNODE = 32;
  public int JJTGET = 33;
  public int JJTRANDOM = 34;
  public int JJTSINE = 35;
  public int JJTCOSINE = 36;
  public int JJTTANGENT = 37;
  public int JJTSQRT = 38;
  public int JJTFLOOR = 39;
  public int JJTCEIL = 40;
  public int JJTROUND = 41;
  public int JJTABS = 42;
  public int JJTLOG = 43;
  public int JJTINT = 44;
  public int JJTLENGTH = 45;
  public int JJTSUBSTRING = 46;
  public int JJTINSERT = 47;
  public int JJTREPLACE = 48;
  public int JJTEXTRACT = 49;
  public int JJTGWINDOWOPEN = 50;
  public int JJTGWINDOWCLOSE = 51;
  public int JJTGCOLOR = 52;
  public int JJTGDRAWOVAL = 53;
  public int JJTGDRAWPOINT = 54;
  public int JJTGFILLOVAL = 55;
  public int JJTGFILLPOINT = 56;
  public int JJTGDRAWLINE = 57;
  public int JJTGDRAWBOX = 58;
  public int JJTGFILLBOX = 59;
  public int JJTGDRAWARC = 60;
  public int JJTGFILLARC = 61;
  public int JJTFILE_OPENR = 62;
  public int JJTFILE_OPENW = 63;
  public int JJTFILE_OPENA = 64;
  public int JJTFILE_CLOSE = 65;
  public int JJTFILE_GETSTR = 66;
  public int JJTFILE_GETLINE = 67;
  public int JJTFILE_PUTSTR = 68;
  public int JJTFILE_PUTLINE = 69;
  public int JJTFILE_FLUSH = 70;
  public int JJTFILE_ISFILE = 71;
  public int JJTFILE_RENAME = 72;
  public int JJTFILE_REMOVE = 73;
  public int JJTIDENT = 74;
  public int JJTARRAYNUM = 75;
  public int JJTFUNCTIONCALL = 76;
  public int JJTRETURN = 77;
  public int JJTLITERAL = 78;
  public int JJTFLOATLITERAL = 79;
  public int JJTSTRLIT = 80;
  public int JJTEOF_STR = 81;


  public String[] jjtNodeName = {
    "IntVUnit",
    "ErrorOccur",
    "Function",
    "Block",
    "FunctionVar",
    "VarDecl",
    "Decl",
    "Array",
    "void",
    "AssignStats",
    "AssignStat",
    "IfStat",
    "WhileStat",
    "RepeatUntil",
    "ForStat",
    "ForStatAdd",
    "GetStat",
    "PutStat",
    "ORNode",
    "ANDNode",
    "NOTNode",
    "EQNode",
    "NTNode",
    "LSNode",
    "GTNode",
    "LENode",
    "GENode",
    "AddNode",
    "SubNode",
    "MulNode",
    "DivNode",
    "SurNode",
    "MinNode",
    "Get",
    "Random",
    "Sine",
    "Cosine",
    "Tangent",
    "Sqrt",
    "Floor",
    "Ceil",
    "Round",
    "Abs",
    "Log",
    "Int",
    "Length",
    "Substring",
    "Insert",
    "Replace",
    "Extract",
    "gWindowOpen",
    "gWindowClose",
    "gColor",
    "gDrawOval",
    "gDrawPoint",
    "gFillOval",
    "gFillPoint",
    "gDrawLine",
    "gDrawBox",
    "gFillBox",
    "gDrawArc",
    "gFillArc",
    "File_openr",
    "File_openw",
    "File_opena",
    "File_close",
    "File_getstr",
    "File_getline",
    "File_putstr",
    "File_putline",
    "File_flush",
    "File_isfile",
    "File_rename",
    "File_remove",
    "Ident",
    "ArrayNum",
    "FunctionCall",
    "Return",
    "Literal",
    "FloatLiteral",
    "Strlit",
    "EOF_STR",
  };
}
