package application.pen;
/* Generated By:JJTree&JavaCC: Do not edit this line. IntVParserConstants.java */
public interface IntVParserConstants {

  int EOF = 0;
  int ADDOP = 8;
  int SUBOP = 9;
  int MULOP = 10;
  int DIVOP = 11;
  int SUROP = 12;
  int ASGNOP = 13;
  int INOP = 14;
  int EQOP = 15;
  int GTOP = 16;
  int GEOP = 17;
  int LSOP = 18;
  int LEOP = 19;
  int NTOP = 20;
  int ANDOP = 21;
  int OROP = 22;
  int NOTOP = 23;
  int LC = 24;
  int RC = 25;
  int LD = 26;
  int RD = 27;
  int LP = 28;
  int RP = 29;
  int SM = 30;
  int CM = 31;
  int CM2 = 32;
  int PN = 33;
  int EOF_STR = 34;
  int NULL_STR = 35;
  int VARINT = 36;
  int VARFLOAT = 37;
  int VARSTRING = 38;
  int PROCEDURAL = 39;
  int ENDPROCEDURAL = 40;
  int FUNCTION = 41;
  int ENDFUNCTION = 42;
  int RETURN = 43;
  int IF = 44;
  int ENDIF = 45;
  int THEN = 46;
  int ELSE = 47;
  int ELSEIF = 48;
  int WHILE = 49;
  int DOWHILE = 50;
  int DOWHILE2 = 51;
  int DOWHILE3 = 52;
  int FOR = 53;
  int FOR2 = 54;
  int FOR3 = 55;
  int FOR4 = 56;
  int FORADD = 57;
  int FORSUB = 58;
  int ENDLOOP = 59;
  int PUTLN = 60;
  int PUT = 61;
  int GET = 62;
  int RANDOM = 63;
  int SIN = 64;
  int COS = 65;
  int TAN = 66;
  int SQRT = 67;
  int FLOOR = 68;
  int CEIL = 69;
  int ROUND = 70;
  int ABS = 71;
  int INT = 72;
  int LOG = 73;
  int LENGTH = 74;
  int SUBSTRING = 75;
  int INSERT = 76;
  int REPLACE = 77;
  int EXTRACT = 78;
  int gWindowOpen = 79;
  int gWindowClose = 80;
  int gColor = 81;
  int gDrawOval = 82;
  int gDrawPoint = 83;
  int gFillOval = 84;
  int gFillPoint = 85;
  int gDrawLine = 86;
  int gDrawBox = 87;
  int gFillBox = 88;
  int gDrawArc = 89;
  int gFillArc = 90;
  int OPENR = 91;
  int OPENW = 92;
  int OPENA = 93;
  int CLOSE = 94;
  int GETSTR = 95;
  int GETLINE = 96;
  int PUTSTR = 97;
  int PUTLINE = 98;
  int FLUSH = 99;
  int ISFILE = 100;
  int RENAME = 101;
  int REMOVE = 102;
  int DIGIT = 103;
  int LETTER = 104;
  int LITERAL = 105;
  int FLOAT_LITERAL = 106;
  int IDENT = 107;
  int STRLIT = 109;
  int COMMENT = 114;

  int DEFAULT = 0;
  int STR = 1;
  int COMM = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"|\"",
    "\"\\uff5c\"",
    "\"\\u3000\"",
    "<ADDOP>",
    "<SUBOP>",
    "<MULOP>",
    "<DIVOP>",
    "<SUROP>",
    "<ASGNOP>",
    "\"->\"",
    "<EQOP>",
    "<GTOP>",
    "<GEOP>",
    "<LSOP>",
    "<LEOP>",
    "<NTOP>",
    "\"\\u304b\\u3064\"",
    "\"\\u307e\\u305f\\u306f\"",
    "\"\\u3067\\u306a\\u3044\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"\\n\"",
    "<CM>",
    "\"\\u3068\"",
    "\".\"",
    "\"EOF\"",
    "\"NULL\"",
    "\"\\u6574\\u6570\"",
    "\"\\u5b9f\\u6570\"",
    "\"\\u6587\\u5b57\\u5217\"",
    "\"\\u624b\\u7d9a\\u304d\"",
    "\"\\u624b\\u7d9a\\u304d\\u7d42\\u4e86\"",
    "\"\\u95a2\\u6570\"",
    "\"\\u95a2\\u6570\\u7d42\\u4e86\"",
    "\"\\u3092\\u8fd4\\u3059\"",
    "\"\\u3082\\u3057\"",
    "<ENDIF>",
    "<THEN>",
    "<ELSE>",
    "<ELSEIF>",
    "<WHILE>",
    "<DOWHILE>",
    "<DOWHILE2>",
    "<DOWHILE3>",
    "\"\\u3092\"",
    "\"\\u304b\\u3089\"",
    "\"\\u307e\\u3067\"",
    "\"\\u305a\\u3064\"",
    "<FORADD>",
    "<FORSUB>",
    "<ENDLOOP>",
    "<PUTLN>",
    "<PUT>",
    "<GET>",
    "<RANDOM>",
    "<SIN>",
    "<COS>",
    "<TAN>",
    "<SQRT>",
    "<FLOOR>",
    "<CEIL>",
    "<ROUND>",
    "<ABS>",
    "<INT>",
    "<LOG>",
    "<LENGTH>",
    "<SUBSTRING>",
    "<INSERT>",
    "<REPLACE>",
    "<EXTRACT>",
    "<gWindowOpen>",
    "<gWindowClose>",
    "<gColor>",
    "<gDrawOval>",
    "<gDrawPoint>",
    "<gFillOval>",
    "<gFillPoint>",
    "<gDrawLine>",
    "<gDrawBox>",
    "<gFillBox>",
    "<gDrawArc>",
    "<gFillArc>",
    "<OPENR>",
    "<OPENW>",
    "<OPENA>",
    "<CLOSE>",
    "<GETSTR>",
    "<GETLINE>",
    "<PUTSTR>",
    "<PUTLINE>",
    "<FLUSH>",
    "<ISFILE>",
    "<RENAME>",
    "<REMOVE>",
    "<DIGIT>",
    "<LETTER>",
    "<LITERAL>",
    "<FLOAT_LITERAL>",
    "<IDENT>",
    "<token of kind 108>",
    "<STRLIT>",
    "<token of kind 110>",
    "\"\\\\n\"",
    "<token of kind 112>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 115>",
    "<token of kind 116>",
  };

}
