/*
		A basic implementation of the JFrame class.
*/
package application.draw;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Insets;
import java.util.Vector;

import nodesystem.StateContainer;
import controlledparts.ControlledButton2;
import controlledparts.FrameWithControlledButton;
import controlledparts.SelectedButton;
import controlledparts.ControlledFrame;
import javax.swing.border.BevelBorder;
import javax.swing.border.EtchedBorder;

/**
* This code was generated using CloudGarden's Jigloo
* SWT/Swing GUI Builder, which is free for non-commercial
* use. If Jigloo is being used commercially (ie, by a corporation,
* company or business for any purpose whatever) then you
* should purchase a license for each developer using Jigloo.
* Please visit www.cloudgarden.com for details.
* Use of Jigloo implies acceptance of these licensing terms.
* *************************************
* A COMMERCIAL LICENSE HAS NOT BEEN PURCHASED
* for this machine, so Jigloo or this code cannot be used legally
* for any corporate or commercial purpose.
* *************************************
*/
public class ColorSelectFrame extends ControlledFrame implements FrameWithControlledButton, StateContainer    
{
    public boolean isDirectOperation()
    {
        return draw.isDirectOperation();
    }

    public int getState()
    {
        return this.currentState;
    }

    public int currentState;

    public void setState(int i)
    {
            ControlledButton2 button=(ControlledButton2)(colorButtons.elementAt(i));
		    draw.colorSelectButton.setBackground( button.getBackground());
		    draw.colorSelectButton.repaint();
		        if(draw.editdispatch!=null){
		            draw.editdispatch.changeColor();
		        }
            this.currentState=i;
            
    }

    public void setWords(){
		this.closeButton.setText(getLclTxt("close"));
    }

    public boolean isControlledByLocalUser()
    {
        // This method is derived from interface FrameWithControlledButton
        // to do: code goes here
        if(draw==null) return true;
        return this.draw.isControlledByLocalUser();
    }

    public void sendEvent(String x)
    {
        draw.sendEvent("dcolor."+x);
    }

    public void unfocusButton(int i)
    {
            SelectedButton button=(SelectedButton)(colorButtons.elementAt(i));
            button.unFocus();
    }

    public void focusButton(int i)
    {
            SelectedButton button=(SelectedButton)(colorButtons.elementAt(i));
            button.focus();
//            button.controlledButton_mouseEntered(null);
    }

    public void clickButton(int i)
    {
        ControlledButton2 t=(ControlledButton2)(colorButtons.elementAt(i));
        t.click();
        this.mouseClickedAtButton(i);
    }

    public void mouseExitedAtButton(int i)
    {
        // This method is derived from interface SelectButtonsFrame
        // to do: code goes here
//        
    }

    public void mouseEnteredAtButton(int i)
    {
        // This method is derived from interface SelectButtonsFrame
        // to do: code goes here
//        draw.sendEvent("dcolor.btn.enter("+i+")\n");
    }

    public void mouseClickedAtButton(int i)
    {
        // This method is derived from interface SelectButtonsFrame
        // to do: code goes here
        SelectedButton t=(SelectedButton)(colorButtons.elementAt(i));
             if(closeButton.getID()==i){
                this.setVisible(false);
                return;
             }
		     if(draw!=null){
		        this.setState(i);
		        this.setVisible(false);
//		        aButtonClicked(i);
		     }
			 
   }

    public void aButtonClicked(int i)
    {
 //       System.out.println("button "+i+" is clicked");
        hide();
    }

    Vector colorButtons;

    public DrawFrame draw;

    public void setDraw(DrawFrame draw)
    {
        this.draw=draw;
    }

	public ColorSelectFrame()
	{
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setTitle("Colors");
		getContentPane().setLayout(null);
		getContentPane().setBackground(new java.awt.Color(204,204,204));
		this.setSize(483, 252);
		setVisible(false);
		whiteButton.setActionCommand("controlledButton2");
		getContentPane().add(whiteButton);
		whiteButton.setBackground(java.awt.Color.white);
		whiteButton.setForeground(java.awt.Color.black);
		whiteButton.setFont(new Font("Dialog", Font.BOLD, 12));
		whiteButton.setBounds(12,12,60,48);
		//$$ etchedBorder1.move(0,249);
		red04Button.setActionCommand("controlledButton2");
		getContentPane().add(red04Button);
		red04Button.setBackground(new java.awt.Color(255,200,200));
		red04Button.setForeground(java.awt.Color.black);
		red04Button.setFont(new Font("Dialog", Font.BOLD, 12));
		red04Button.setBounds(72,12,48,24);
		green04Button.setActionCommand("controlledButton2");
		getContentPane().add(green04Button);
		green04Button.setBackground(new java.awt.Color(200,255,200));
		green04Button.setForeground(java.awt.Color.black);
		green04Button.setFont(new Font("Dialog", Font.BOLD, 12));
		green04Button.setBounds(204,12,48,24);
		blue04Button.setActionCommand("controlledButton2");
		getContentPane().add(blue04Button);
		blue04Button.setBackground(new java.awt.Color(200,200,255));
		blue04Button.setForeground(java.awt.Color.black);
		blue04Button.setFont(new Font("Dialog", Font.BOLD, 12));
		blue04Button.setBounds(336,12,48,24);
		lightGrayButton.setActionCommand("controlledButton2");
//		lightGrayButton.setBorder(etchedBorder1);
		getContentPane().add(lightGrayButton);
		lightGrayButton.setBackground(java.awt.Color.lightGray);
		lightGrayButton.setForeground(java.awt.Color.black);
		lightGrayButton.setFont(new Font("Dialog", Font.BOLD, 12));
		lightGrayButton.setBounds(12,60,60,36);
		red03Button.setActionCommand("controlledButton2");
		getContentPane().add(red03Button);
		red03Button.setBackground(new java.awt.Color(255,100,100));
		red03Button.setForeground(java.awt.Color.black);
		red03Button.setFont(new Font("Dialog", Font.BOLD, 12));
		red03Button.setBounds(72,36,48,24);
		green03Button.setActionCommand("controlledButton2");
		getContentPane().add(green03Button);
		green03Button.setBackground(new java.awt.Color(100,255,100));
		green03Button.setForeground(java.awt.Color.black);
		green03Button.setFont(new Font("Dialog", Font.BOLD, 12));
		green03Button.setBounds(204,36,48,24);
		blue03Button.setActionCommand("controlledButton2");
		getContentPane().add(blue03Button);
		blue03Button.setBackground(new java.awt.Color(100,100,255));
		blue03Button.setForeground(java.awt.Color.black);
		blue03Button.setFont(new Font("Dialog", Font.BOLD, 12));
		blue03Button.setBounds(336,36,48,24);
		darkGrayButton.setActionCommand("controlledButton2");
		getContentPane().add(darkGrayButton);
		darkGrayButton.setBackground(java.awt.Color.darkGray);
		darkGrayButton.setForeground(java.awt.Color.black);
		darkGrayButton.setFont(new Font("Dialog", Font.BOLD, 12));
		darkGrayButton.setBounds(12,96,60,48);
		red02Button.setActionCommand("controlledButton2");
		getContentPane().add(red02Button);
		red02Button.setBackground(new java.awt.Color(255,50,50));
		red02Button.setForeground(java.awt.Color.black);
		red02Button.setFont(new Font("Dialog", Font.BOLD, 12));
		red02Button.setBounds(72,60,48,24);
		green02Button.setActionCommand("controlledButton2");
		getContentPane().add(green02Button);
		green02Button.setBackground(new java.awt.Color(50,255,50));
		green02Button.setForeground(java.awt.Color.black);
		green02Button.setFont(new Font("Dialog", Font.BOLD, 12));
		green02Button.setBounds(204,60,48,24);
		blue02Button.setActionCommand("controlledButton2");
		getContentPane().add(blue02Button);
		blue02Button.setBackground(new java.awt.Color(50,50,255));
		blue02Button.setForeground(java.awt.Color.black);
		blue02Button.setFont(new Font("Dialog", Font.BOLD, 12));
		blue02Button.setBounds(336,60,48,24);
		blackButton.setActionCommand("controlledButton2");
		getContentPane().add(blackButton);
		blackButton.setBackground(java.awt.Color.black);
		blackButton.setForeground(java.awt.Color.black);
		blackButton.setFont(new Font("Dialog", Font.BOLD, 12));
		blackButton.setBounds(12,144,60,48);
		red01Button.setText("r");
		red01Button.setActionCommand("r");
		getContentPane().add(red01Button);
		red01Button.setBackground(java.awt.Color.red);
		red01Button.setForeground(java.awt.Color.black);
		red01Button.setFont(new Font("Dialog", Font.BOLD, 12));
		red01Button.setBounds(72,84,48,36);
		green01Button.setText("g");
		green01Button.setActionCommand("g");
		getContentPane().add(green01Button);
		green01Button.setBackground(java.awt.Color.green);
		green01Button.setForeground(java.awt.Color.black);
		green01Button.setFont(new Font("Dialog", Font.BOLD, 12));
		green01Button.setBounds(204,84,48,36);
		blue01Button.setText("b");
		blue01Button.setActionCommand("b");
		getContentPane().add(blue01Button);
		blue01Button.setBackground(java.awt.Color.blue);
		blue01Button.setForeground(java.awt.Color.black);
		blue01Button.setFont(new Font("Dialog", Font.BOLD, 12));
		blue01Button.setBounds(336,84,48,36);
		yellow04Button.setActionCommand("controlledButton2");
		getContentPane().add(yellow04Button);
		yellow04Button.setBackground(new java.awt.Color(255,255,200));
		yellow04Button.setForeground(java.awt.Color.black);
		yellow04Button.setFont(new Font("Dialog", Font.BOLD, 12));
		yellow04Button.setBounds(144,12,36,24);
		yellow03Button.setActionCommand("controlledButton2");
		getContentPane().add(yellow03Button);
		yellow03Button.setBackground(new java.awt.Color(255,255,100));
		yellow03Button.setForeground(java.awt.Color.black);
		yellow03Button.setFont(new Font("Dialog", Font.BOLD, 12));
		yellow03Button.setBounds(144,36,36,24);
		yellow02Button.setActionCommand("controlledButton2");
		getContentPane().add(yellow02Button);
		yellow02Button.setBackground(new java.awt.Color(255,255,50));
		yellow02Button.setForeground(java.awt.Color.black);
		yellow02Button.setFont(new Font("Dialog", Font.BOLD, 12));
		yellow02Button.setBounds(144,60,36,24);
		yellow01Button.setActionCommand("controlledButton2");
		getContentPane().add(yellow01Button);
		yellow01Button.setBackground(java.awt.Color.yellow);
		yellow01Button.setForeground(java.awt.Color.black);
		yellow01Button.setFont(new Font("Dialog", Font.BOLD, 12));
		yellow01Button.setBounds(144,84,36,36);
		syan04Button.setActionCommand("controlledButton2");
		getContentPane().add(syan04Button);
		syan04Button.setBackground(new java.awt.Color(200,255,255));
		syan04Button.setForeground(java.awt.Color.black);
		syan04Button.setFont(new Font("Dialog", Font.BOLD, 12));
		syan04Button.setBounds(276,12,36,24);
		cyan03Button.setActionCommand("controlledButton2");
		getContentPane().add(cyan03Button);
		cyan03Button.setBackground(new java.awt.Color(100,255,255));
		cyan03Button.setForeground(java.awt.Color.black);
		cyan03Button.setFont(new Font("Dialog", Font.BOLD, 12));
		cyan03Button.setBounds(276,36,36,24);
		syan02Button.setActionCommand("controlledButton2");
		getContentPane().add(syan02Button);
		syan02Button.setBackground(new java.awt.Color(50,255,255));
		syan02Button.setForeground(java.awt.Color.black);
		syan02Button.setFont(new Font("Dialog", Font.BOLD, 12));
		syan02Button.setBounds(276,60,36,24);
		cyan01Button.setActionCommand("controlledButton2");
		getContentPane().add(cyan01Button);
		cyan01Button.setBackground(java.awt.Color.cyan);
		cyan01Button.setForeground(java.awt.Color.black);
		cyan01Button.setFont(new Font("Dialog", Font.BOLD, 12));
		cyan01Button.setBounds(276,84,36,36);
		magenta04Button.setActionCommand("controlledButton2");
		getContentPane().add(magenta04Button);
		magenta04Button.setBackground(new java.awt.Color(255,200,255));
		magenta04Button.setForeground(java.awt.Color.black);
		magenta04Button.setFont(new Font("Dialog", Font.BOLD, 12));
		magenta04Button.setBounds(408,12,36,24);
		magenta03Button.setActionCommand("controlledButton2");
		getContentPane().add(magenta03Button);
		magenta03Button.setBackground(new java.awt.Color(255,100,255));
		magenta03Button.setForeground(java.awt.Color.black);
		magenta03Button.setFont(new Font("Dialog", Font.BOLD, 12));
		magenta03Button.setBounds(408,36,36,24);
		magenta02Button.setActionCommand("controlledButton2");
		getContentPane().add(magenta02Button);
		magenta02Button.setBackground(new java.awt.Color(255,50,255));
		magenta02Button.setForeground(java.awt.Color.black);
		magenta02Button.setFont(new Font("Dialog", Font.BOLD, 12));
		magenta02Button.setBounds(408,60,36,24);
		magenta01Button.setActionCommand("controlledButton2");
		getContentPane().add(magenta01Button);
		magenta01Button.setBackground(java.awt.Color.magenta);
		magenta01Button.setForeground(java.awt.Color.black);
		magenta01Button.setFont(new Font("Dialog", Font.BOLD, 12));
		magenta01Button.setBounds(408,84,36,36);
		//$$ bevelBorder1.move(24,249);
		//$$ matteBorder1.move(48,249);
		controlledButton21.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton21);
		controlledButton21.setBackground(new java.awt.Color(255,221,187));
		controlledButton21.setForeground(java.awt.Color.black);
		controlledButton21.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton21.setBounds(120,12,24,24);
		controlledButton22.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton22);
		controlledButton22.setBackground(new java.awt.Color(255,175,96));
		controlledButton22.setForeground(java.awt.Color.black);
		controlledButton22.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton22.setBounds(120,36,24,24);
		controlledButton23.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton23);
		controlledButton23.setBackground(new java.awt.Color(255,155,55));
		controlledButton23.setForeground(java.awt.Color.black);
		controlledButton23.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton23.setBounds(120,60,24,24);
		controlledButton24.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton24);
		controlledButton24.setBackground(new java.awt.Color(251,125,0));
		controlledButton24.setForeground(java.awt.Color.black);
		controlledButton24.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton24.setBounds(120,84,24,36);
		controlledButton25.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton25);
		controlledButton25.setBackground(new java.awt.Color(221,255,187));
		controlledButton25.setForeground(java.awt.Color.black);
		controlledButton25.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton25.setBounds(180,12,24,24);
		controlledButton26.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton26);
		controlledButton26.setBackground(new java.awt.Color(175,255,96));
		controlledButton26.setForeground(java.awt.Color.black);
		controlledButton26.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton26.setBounds(180,36,24,24);
		controlledButton27.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton27);
		controlledButton27.setBackground(new java.awt.Color(155,255,55));
		controlledButton27.setForeground(java.awt.Color.black);
		controlledButton27.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton27.setBounds(180,60,24,24);
		controlledButton28.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton28);
		controlledButton28.setBackground(new java.awt.Color(125,251,0));
		controlledButton28.setForeground(java.awt.Color.black);
		controlledButton28.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton28.setBounds(180,84,24,36);
		controlledButton29.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton29);
		controlledButton29.setBackground(new java.awt.Color(187,255,221));
		controlledButton29.setForeground(java.awt.Color.black);
		controlledButton29.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton29.setBounds(252,12,24,24);
		controlledButton210.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton210);
		controlledButton210.setBackground(new java.awt.Color(96,255,175));
		controlledButton210.setForeground(java.awt.Color.black);
		controlledButton210.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton210.setBounds(252,36,24,24);
		controlledButton211.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton211);
		controlledButton211.setBackground(new java.awt.Color(55,255,155));
		controlledButton211.setForeground(java.awt.Color.black);
		controlledButton211.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton211.setBounds(252,60,24,24);
		controlledButton212.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton212);
		controlledButton212.setBackground(new java.awt.Color(0,251,125));
		controlledButton212.setForeground(java.awt.Color.black);
		controlledButton212.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton212.setBounds(252,84,24,36);
		controlledButton213.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton213);
		controlledButton213.setBackground(new java.awt.Color(187,221,255));
		controlledButton213.setForeground(java.awt.Color.black);
		controlledButton213.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton213.setBounds(312,12,24,24);
		controlledButton214.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton214);
		controlledButton214.setBackground(new java.awt.Color(96,175,255));
		controlledButton214.setForeground(java.awt.Color.black);
		controlledButton214.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton214.setBounds(312,36,24,24);
		controlledButton215.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton215);
		controlledButton215.setBackground(new java.awt.Color(55,155,255));
		controlledButton215.setForeground(java.awt.Color.black);
		controlledButton215.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton215.setBounds(312,60,24,24);
		controlledButton216.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton216);
		controlledButton216.setBackground(new java.awt.Color(0,125,251));
		controlledButton216.setForeground(java.awt.Color.black);
		controlledButton216.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton216.setBounds(312,84,24,36);
		controlledButton217.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton217);
		controlledButton217.setBackground(new java.awt.Color(221,187,255));
		controlledButton217.setForeground(java.awt.Color.black);
		controlledButton217.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton217.setBounds(384,12,24,24);
		controlledButton218.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton218);
		controlledButton218.setBackground(new java.awt.Color(175,96,255));
		controlledButton218.setForeground(java.awt.Color.black);
		controlledButton218.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton218.setBounds(384,36,24,24);
		controlledButton219.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton219);
		controlledButton219.setBackground(new java.awt.Color(155,55,255));
		controlledButton219.setForeground(java.awt.Color.black);
		controlledButton219.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton219.setBounds(384,60,24,24);
		controlledButton220.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton220);
		controlledButton220.setBackground(new java.awt.Color(125,0,251));
		controlledButton220.setForeground(java.awt.Color.black);
		controlledButton220.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton220.setBounds(384,84,24,36);
		controlledButton222.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton222);
		controlledButton222.setBackground(new java.awt.Color(213,0,0));
		controlledButton222.setForeground(java.awt.Color.black);
		controlledButton222.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton222.setBounds(72,120,48,24);
		controlledButton223.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton223);
		controlledButton223.setBackground(new java.awt.Color(0,213,0));
		controlledButton223.setForeground(java.awt.Color.black);
		controlledButton223.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton223.setBounds(204,120,48,24);
		controlledButton224.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton224);
		controlledButton224.setBackground(new java.awt.Color(0,0,213));
		controlledButton224.setForeground(java.awt.Color.black);
		controlledButton224.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton224.setBounds(336,120,48,24);
		controlledButton225.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton225);
		controlledButton225.setBackground(new java.awt.Color(213,213,0));
		controlledButton225.setForeground(java.awt.Color.black);
		controlledButton225.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton225.setBounds(144,120,36,24);
		controlledButton226.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton226);
		controlledButton226.setBackground(new java.awt.Color(0,213,213));
		controlledButton226.setForeground(java.awt.Color.black);
		controlledButton226.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton226.setBounds(276,120,36,24);
		controlledButton227.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton227);
		controlledButton227.setBackground(new java.awt.Color(213,0,213));
		controlledButton227.setForeground(java.awt.Color.black);
		controlledButton227.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton227.setBounds(408,120,36,24);
		controlledButton228.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton228);
		controlledButton228.setBackground(new java.awt.Color(213,106,0));
		controlledButton228.setForeground(java.awt.Color.black);
		controlledButton228.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton228.setBounds(120,120,24,24);
		controlledButton229.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton229);
		controlledButton229.setBackground(new java.awt.Color(106,213,0));
		controlledButton229.setForeground(java.awt.Color.black);
		controlledButton229.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton229.setBounds(180,120,24,24);
		controlledButton230.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton230);
		controlledButton230.setBackground(new java.awt.Color(0,213,106));
		controlledButton230.setForeground(java.awt.Color.black);
		controlledButton230.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton230.setBounds(252,120,24,24);
		controlledButton231.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton231);
		controlledButton231.setBackground(new java.awt.Color(0,106,213));
		controlledButton231.setForeground(java.awt.Color.black);
		controlledButton231.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton231.setBounds(312,120,24,24);
		controlledButton232.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton232);
		controlledButton232.setBackground(new java.awt.Color(106,0,213));
		controlledButton232.setForeground(java.awt.Color.black);
		controlledButton232.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton232.setBounds(384,120,24,24);
		controlledButton221.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton221);
		controlledButton221.setBackground(new java.awt.Color(106,0,0));
		controlledButton221.setForeground(java.awt.Color.black);
		controlledButton221.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton221.setBounds(72,144,48,24);
		controlledButton233.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton233);
		controlledButton233.setBackground(new java.awt.Color(0,106,0));
		controlledButton233.setForeground(java.awt.Color.black);
		controlledButton233.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton233.setBounds(204,144,48,24);
		controlledButton234.setText("controlledButton2");
		controlledButton234.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton234);
		controlledButton234.setBackground(new java.awt.Color(0,0,106));
		controlledButton234.setForeground(java.awt.Color.black);
		controlledButton234.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton234.setBounds(336,144,48,24);
		controlledButton235.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton235);
		controlledButton235.setBackground(new java.awt.Color(106,106,0));
		controlledButton235.setForeground(java.awt.Color.black);
		controlledButton235.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton235.setBounds(144,144,36,24);
		controlledButton236.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton236);
		controlledButton236.setBackground(new java.awt.Color(0,106,106));
		controlledButton236.setForeground(java.awt.Color.black);
		controlledButton236.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton236.setBounds(276,144,36,24);
		controlledButton237.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton237);
		controlledButton237.setBackground(new java.awt.Color(106,0,106));
		controlledButton237.setForeground(java.awt.Color.black);
		controlledButton237.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton237.setBounds(408,144,36,24);
		controlledButton238.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton238);
		controlledButton238.setBackground(new java.awt.Color(106,53,0));
		controlledButton238.setForeground(java.awt.Color.black);
		controlledButton238.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton238.setBounds(120,144,24,24);
		controlledButton239.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton239);
		controlledButton239.setBackground(new java.awt.Color(53,106,0));
		controlledButton239.setForeground(java.awt.Color.black);
		controlledButton239.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton239.setBounds(180,144,24,24);
		controlledButton240.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton240);
		controlledButton240.setBackground(new java.awt.Color(0,106,53));
		controlledButton240.setForeground(java.awt.Color.black);
		controlledButton240.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton240.setBounds(252,144,24,24);
		controlledButton241.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton241);
		controlledButton241.setBackground(new java.awt.Color(0,53,106));
		controlledButton241.setForeground(java.awt.Color.black);
		controlledButton241.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton241.setBounds(312,144,24,24);
		controlledButton242.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton242);
		controlledButton242.setBackground(new java.awt.Color(53,0,106));
		controlledButton242.setForeground(java.awt.Color.black);
		controlledButton242.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton242.setBounds(384,144,24,24);
		controlledButton243.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton243);
		controlledButton243.setBackground(new java.awt.Color(53,0,0));
		controlledButton243.setForeground(java.awt.Color.black);
		controlledButton243.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton243.setBounds(72,168,48,24);
		controlledButton244.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton244);
		controlledButton244.setBackground(new java.awt.Color(0,53,0));
		controlledButton244.setForeground(java.awt.Color.black);
		controlledButton244.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton244.setBounds(204,168,48,24);
		controlledButton245.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton245);
		controlledButton245.setBackground(new java.awt.Color(0,0,53));
		controlledButton245.setForeground(java.awt.Color.black);
		controlledButton245.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton245.setBounds(336,168,48,24);
		controlledButton246.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton246);
		controlledButton246.setBackground(new java.awt.Color(53,53,0));
		controlledButton246.setForeground(java.awt.Color.black);
		controlledButton246.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton246.setBounds(144,168,36,24);
		controlledButton247.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton247);
		controlledButton247.setBackground(new java.awt.Color(0,53,53));
		controlledButton247.setForeground(java.awt.Color.black);
		controlledButton247.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton247.setBounds(276,168,36,24);
		controlledButton248.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton248);
		controlledButton248.setBackground(new java.awt.Color(53,0,53));
		controlledButton248.setForeground(java.awt.Color.black);
		controlledButton248.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton248.setBounds(408,168,36,24);
		controlledButton249.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton249);
		controlledButton249.setBackground(new java.awt.Color(53,27,0));
		controlledButton249.setForeground(java.awt.Color.black);
		controlledButton249.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton249.setBounds(120,168,24,24);
		controlledButton250.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton250);
		controlledButton250.setBackground(new java.awt.Color(27,53,0));
		controlledButton250.setForeground(java.awt.Color.black);
		controlledButton250.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton250.setBounds(180,168,24,24);
		controlledButton251.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton251);
		controlledButton251.setBackground(new java.awt.Color(0,53,27));
		controlledButton251.setForeground(java.awt.Color.black);
		controlledButton251.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton251.setBounds(252,168,24,24);
		controlledButton252.setText("controlledButton2");
		controlledButton252.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton252);
		controlledButton252.setBackground(new java.awt.Color(0,27,53));
		controlledButton252.setForeground(java.awt.Color.black);
		controlledButton252.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton252.setBounds(312,168,24,24);
		controlledButton253.setText("controlledButton2");
		controlledButton253.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton253);
		controlledButton253.setBackground(new java.awt.Color(27,0,53));
		controlledButton253.setForeground(java.awt.Color.black);
		controlledButton253.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton253.setBounds(384,168,24,24);
		controlledButton254.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton254);
		controlledButton254.setBackground(new java.awt.Color(255,187,221));
		controlledButton254.setForeground(java.awt.Color.black);
		controlledButton254.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton254.setBounds(444,12,24,24);
		controlledButton255.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton255);
		controlledButton255.setBackground(new java.awt.Color(255,96,175));
		controlledButton255.setForeground(java.awt.Color.black);
		controlledButton255.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton255.setBounds(444,36,24,24);
		controlledButton256.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton256);
		controlledButton256.setBackground(new java.awt.Color(255,55,155));
		controlledButton256.setForeground(java.awt.Color.black);
		controlledButton256.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton256.setBounds(444,60,24,24);
		controlledButton257.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton257);
		controlledButton257.setBackground(new java.awt.Color(251,0,125));
		controlledButton257.setForeground(java.awt.Color.black);
		controlledButton257.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton257.setBounds(444,84,24,36);
		controlledButton258.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton258);
		controlledButton258.setBackground(new java.awt.Color(213,0,106));
		controlledButton258.setForeground(java.awt.Color.black);
		controlledButton258.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton258.setBounds(444,120,24,24);
		controlledButton259.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton259);
		controlledButton259.setBackground(new java.awt.Color(106,0,53));
		controlledButton259.setForeground(java.awt.Color.black);
		controlledButton259.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton259.setBounds(444,144,24,24);
		controlledButton260.setText("controlledButton2");
		controlledButton260.setActionCommand("controlledButton2");
		getContentPane().add(controlledButton260);
		controlledButton260.setBackground(new java.awt.Color(53,0,27));
		controlledButton260.setForeground(java.awt.Color.black);
		controlledButton260.setFont(new Font("Dialog", Font.BOLD, 12));
		controlledButton260.setBounds(444,168,24,24);
		closeButton.setText("close");
		closeButton.setActionCommand("close");
		getContentPane().add(closeButton);
		closeButton.setBackground(new java.awt.Color(204,204,204));
		closeButton.setForeground(java.awt.Color.black);
		closeButton.setFont(new Font("Dialog", Font.BOLD, 12));
		closeButton.setBounds(120,204,204,24);
		//}}

		//{{INIT_MENUS
		//}}
	
		//{{REGISTER_LISTENERS
		SymAction lSymAction = new SymAction();
//		whiteButton.addActionListener(lSymAction);
		closeButton.addActionListener(lSymAction);
		SymComponent aSymComponent = new SymComponent();
		this.addComponentListener(aSymComponent);
		//}}
		
		colorButtons=new Vector();
		colorButtons.addElement(whiteButton);
		colorButtons.addElement(red04Button);
		colorButtons.addElement(green04Button);
		colorButtons.addElement(blue04Button);
		colorButtons.addElement(lightGrayButton);
		colorButtons.addElement(red03Button);
		colorButtons.addElement(green03Button);
		colorButtons.addElement(blue03Button);
		colorButtons.addElement(darkGrayButton);
		colorButtons.addElement(red02Button);
		colorButtons.addElement(green02Button);
		colorButtons.addElement(blue02Button);
		colorButtons.addElement(blackButton);
		colorButtons.addElement(red01Button);
		colorButtons.addElement(green01Button);
		colorButtons.addElement(blue01Button);
		colorButtons.addElement(yellow04Button);
		colorButtons.addElement(yellow03Button);
		colorButtons.addElement(yellow02Button);
		colorButtons.addElement(yellow01Button);
		colorButtons.addElement(syan04Button);
		colorButtons.addElement(cyan03Button);
		colorButtons.addElement(syan02Button);
		colorButtons.addElement(cyan01Button);
		colorButtons.addElement(magenta04Button);
		colorButtons.addElement(magenta03Button);
		colorButtons.addElement(magenta02Button);
		colorButtons.addElement(magenta01Button);
		colorButtons.addElement(controlledButton21);
		colorButtons.addElement(controlledButton22);
		colorButtons.addElement(controlledButton23);
		colorButtons.addElement(controlledButton24);
		colorButtons.addElement(controlledButton25);
		colorButtons.addElement(controlledButton26);
		colorButtons.addElement(controlledButton27);
		colorButtons.addElement(controlledButton28);
		colorButtons.addElement(controlledButton29);
		colorButtons.addElement(controlledButton210);
		colorButtons.addElement(controlledButton211);
		colorButtons.addElement(controlledButton212);
		colorButtons.addElement(controlledButton213);
		colorButtons.addElement(controlledButton214);
		colorButtons.addElement(controlledButton215);
		colorButtons.addElement(controlledButton216);
		colorButtons.addElement(controlledButton217);
		colorButtons.addElement(controlledButton218);
		colorButtons.addElement(controlledButton219);
		colorButtons.addElement(controlledButton220);
		colorButtons.addElement(controlledButton221);
		colorButtons.addElement(controlledButton222);
		colorButtons.addElement(controlledButton223);
		colorButtons.addElement(controlledButton224);
		colorButtons.addElement(controlledButton225);
		colorButtons.addElement(controlledButton226);
		colorButtons.addElement(controlledButton227);
		colorButtons.addElement(controlledButton228);
		colorButtons.addElement(controlledButton229);
		colorButtons.addElement(controlledButton230);
		colorButtons.addElement(controlledButton231);
		colorButtons.addElement(controlledButton232);
		colorButtons.addElement(controlledButton233);
		colorButtons.addElement(controlledButton234);
		colorButtons.addElement(controlledButton235);
		colorButtons.addElement(controlledButton236);
		colorButtons.addElement(controlledButton237);
		colorButtons.addElement(controlledButton238);
		colorButtons.addElement(controlledButton239);
		colorButtons.addElement(controlledButton240);
		colorButtons.addElement(controlledButton241);
		colorButtons.addElement(controlledButton242);
		colorButtons.addElement(controlledButton243);
		colorButtons.addElement(controlledButton244);
		colorButtons.addElement(controlledButton245);
		colorButtons.addElement(controlledButton246);
		colorButtons.addElement(controlledButton247);
		colorButtons.addElement(controlledButton248);
		colorButtons.addElement(controlledButton249);
		colorButtons.addElement(controlledButton250);
		colorButtons.addElement(controlledButton251);
		colorButtons.addElement(controlledButton252);
		colorButtons.addElement(controlledButton253);
		colorButtons.addElement(controlledButton254);
		colorButtons.addElement(controlledButton255);
		colorButtons.addElement(controlledButton256);
		colorButtons.addElement(controlledButton257);
		colorButtons.addElement(controlledButton258);
		colorButtons.addElement(controlledButton259);
		colorButtons.addElement(controlledButton260);
		
		int buttonNumber=colorButtons.size();
		
        for(int i=0;i<buttonNumber;i++){
            ControlledButton2 b=(ControlledButton2)(colorButtons.elementAt(i));
            b.setFrame(this);
            b.setBorder1(bevelBorder1);
//            b.setBorder2(this.etchedBorder1);
            b.setBorder2(bevelBorder2);
            b.setID(i);
	    	b.addActionListener(lSymAction);
        }
        
     	colorButtons.addElement(this.closeButton);
     	closeButton.setFrame(this);
     	closeButton.setID(buttonNumber);
	
	}

	public ColorSelectFrame(String sTitle)
	{
		this();
		setTitle(sTitle);
	}

	public void setVisible(boolean b)
	{
		if (b)
			setLocation(50, 50);
		super.setVisible(b);
	}

	static public void main(String args[])
	{
		(new ColorSelectFrame()).setVisible(true);
	}

	public void addNotify()
	{
		// Record the size of the window prior to calling parents addNotify.
		Dimension size = getSize();

		super.addNotify();

		if (frameSizeAdjusted)
			return;
		frameSizeAdjusted = true;

		// Adjust size of frame according to the insets and menu bar
		Insets insets = getInsets();
		javax.swing.JMenuBar menuBar = getRootPane().getJMenuBar();
		int menuBarHeight = 0;
		if (menuBar != null)
			menuBarHeight = menuBar.getPreferredSize().height;
		setSize(insets.left + insets.right + size.width, insets.top + insets.bottom + size.height + menuBarHeight);
	}

	// Used by addNotify
	boolean frameSizeAdjusted = false;

	//{{DECLARE_CONTROLS
	controlledparts.ControlledButton2 whiteButton = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 red04Button = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 green04Button = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 blue04Button = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 lightGrayButton = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 red03Button = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 green03Button = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 blue03Button = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 darkGrayButton = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 red02Button = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 green02Button = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 blue02Button = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 blackButton = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 red01Button = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 green01Button = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 blue01Button = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 yellow04Button = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 yellow03Button = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 yellow02Button = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 yellow01Button = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 syan04Button = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 cyan03Button = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 syan02Button = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 cyan01Button = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 magenta04Button = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 magenta03Button = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 magenta02Button = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 magenta01Button = new controlledparts.ControlledButton2();
    BevelBorder bevelBorder1 = new BevelBorder(BevelBorder.RAISED);
	BevelBorder bevelBorder2 = new BevelBorder(BevelBorder.LOWERED);
    EtchedBorder etchedBorder1 = new EtchedBorder();
//	MatteBorder matteBorder1 = new MatteBorder(MatteBorder.RAISED);
	controlledparts.ControlledButton2 controlledButton21 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton22 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton23 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton24 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton25 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton26 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton27 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton28 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton29 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton210 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton211 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton212 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton213 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton214 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton215 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton216 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton217 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton218 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton219 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton220 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton222 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton223 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton224 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton225 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton226 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton227 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton228 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton229 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton230 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton231 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton232 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton221 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton233 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton234 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton235 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton236 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton237 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton238 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton239 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton240 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton241 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton242 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton243 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton244 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton245 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton246 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton247 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton248 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton249 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton250 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton251 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton252 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton253 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton254 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton255 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton256 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton257 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton258 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton259 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton2 controlledButton260 = new controlledparts.ControlledButton2();
	controlledparts.ControlledButton closeButton = new controlledparts.ControlledButton();
	//}}

	//{{DECLARE_MENUS
	//}}


	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
		    /*
			Object object = event.getSource();
			if(object==closeButton) { return; }
            int buttonNumber=colorButtons.size();
            for(int i=0;i<buttonNumber-1;i++){
                ControlledButton2 b=(ControlledButton2)(colorButtons.elementAt(i));
                if(object == b){ 
       //              mouseClickedAtButton(i);
                }
            }
            */
            
		}
	}

	void whiteButton_actionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		whiteButton_actionPerformed_Interaction1(event);
	}

	void whiteButton_actionPerformed_Interaction1(java.awt.event.ActionEvent event)
	{
		try {
//			whiteButton.show();
		} catch (Exception e) {
		}
	}

	void closeButton_actionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		closeButton_actionPerformed_Interaction1(event);
	}

	void closeButton_actionPerformed_Interaction1(java.awt.event.ActionEvent event)
	{
		try {
//			closeButton.show();
		} catch (java.lang.Exception e) {
		}
	}

	class SymComponent extends java.awt.event.ComponentAdapter
	{
		public void componentMoved(java.awt.event.ComponentEvent event)
		{
			Object object = event.getSource();
			if (object == ColorSelectFrame.this)
				ColorSelectFrame_componentMoved(event);
		}
	}

	void ColorSelectFrame_componentMoved(java.awt.event.ComponentEvent event)
	{
		// to do: code goes here.
			 
		ColorSelectFrame_componentMoved_Interaction1(event);
	}

	void ColorSelectFrame_componentMoved_Interaction1(java.awt.event.ComponentEvent event)
	{
		try {
//			this.move(x, y);
		} catch (java.lang.Exception e) {
		}
		
	}
}