/*
		A basic implementation of the JFrame class.
*/
package application.draw;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Insets;
import java.net.URL;
import java.util.Vector;
import javax.swing.ImageIcon;

import nodesystem.StateContainer;
import controlledparts.ControlledButton;
import controlledparts.FrameWithControlledButton;
import controlledparts.SelectedButton;

public class WidthSelectFrame extends javax.swing.JFrame implements FrameWithControlledButton, StateContainer    
{
    public boolean isDirectOperation()
    {
        return draw.isDirectOperation();
    }

    public int getState()
    {
        return this.currentState;
    }

    public int currentState;

    public void setState(int i)
    {
        ControlledButton b=(ControlledButton)(buttons.elementAt(i));
        draw.lineWidthSelectButton.setIcon(b.getIcon());
        draw.lineWidthSelectButton.setText(b.getText());
        draw.lineWidthSelectButton.repaint();
        draw.editdispatch.changeWidth();
        this.currentState=i;
    }

    public boolean isControlledByLocalUser()
    {
        // This method is derived from interface FrameWithControlledButton
        // to do: code goes here
        return draw.isControlledByLocalUser();
    }

    public void sendEvent(String x)
    {
        draw.sendEvent("dwidth."+x);
    }

    public void clickButton(int i)
    {
        ControlledButton b=(ControlledButton)(buttons.elementAt(i));
        b.click();
        this.mouseClickedAtButton(i);
    }

    public void unfocusButton(int i)
    {
            SelectedButton button=(SelectedButton)(buttons.elementAt(i));
            button.controlledButton_mouseExited(null);
    }

    public void focusButton(int i)
    {
            SelectedButton button=(SelectedButton)(buttons.elementAt(i));
            button.focus();
    }

    Vector buttons;

    public void mouseExitedAtButton(int i)
    {
        // This method is derived from interface SelectButtonsFrame
        // to do: code goes here
//        draw.sendEvent("dwidth.btn.exit("+i+")\n");
   }

    public void mouseEnteredAtButton(int i)
    {
        // This method is derived from interface SelectButtonsFrame
        // to do: code goes here
//        draw.sendEvent("dwidth.btn.enter("+i+")\n");
    }

    public void mouseClickedAtButton(int i)
    {
        // This method is derived from interface SelectButtonsFrame
        // to do: code goes here
        if(this.closeButton.getID()==i){
            this.hide();
            return;
        }
        this.setState(i);
        this.hide();
    }

    public DrawFrame draw;

    public void setDraw(DrawFrame draw)
    {
        this.draw=draw;
    }

    public void setIcons(String iconPlace){
    	try{
   		 this.width1.setIcon(new ImageIcon(new URL(iconPlace+"width1.gif")));
		 this.width2.setIcon(new ImageIcon(new URL(iconPlace+"width2.gif")));
		 this.width3.setIcon(new ImageIcon(new URL(iconPlace+"width3.gif")));
		 this.width4.setIcon(new ImageIcon(new URL(iconPlace+"width4.gif")));
		 this.width5.setIcon(new ImageIcon(new URL(iconPlace+"width5.gif")));
    		
    	}
    	catch(Exception e){
    		
    	}
    }
    
	public WidthSelectFrame()
	{
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setTitle("Line Width");
		getContentPane().setLayout(null);
		getContentPane().setBackground(new java.awt.Color(204,204,204));
		setSize(164,207);
		setVisible(false);
		width1.setText("1");
		width1.setActionCommand("1");
		getContentPane().add(width1);
		width1.setBackground(new java.awt.Color(204,204,204));
		width1.setForeground(java.awt.Color.black);
		width1.setFont(new Font("Dialog", Font.BOLD, 12));
		width1.setBounds(12,12,144,24);
		width2.setText("2");
		width2.setActionCommand("2");
		getContentPane().add(width2);
		width2.setBackground(new java.awt.Color(204,204,204));
		width2.setForeground(java.awt.Color.black);
		width2.setFont(new Font("Dialog", Font.BOLD, 12));
		width2.setBounds(12,36,144,24);
		width3.setText("3");
		width3.setActionCommand("3");
		getContentPane().add(width3);
		width3.setBackground(new java.awt.Color(204,204,204));
		width3.setForeground(java.awt.Color.black);
		width3.setFont(new Font("Dialog", Font.BOLD, 12));
		width3.setBounds(12,60,144,24);
		width4.setText("4");
		width4.setActionCommand("4");
		getContentPane().add(width4);
		width4.setBackground(new java.awt.Color(204,204,204));
		width4.setForeground(java.awt.Color.black);
		width4.setFont(new Font("Dialog", Font.BOLD, 12));
		width4.setBounds(12,84,144,24);
		width5.setText("5");
		width5.setActionCommand("5");
		getContentPane().add(width5);
		width5.setBackground(new java.awt.Color(204,204,204));
		width5.setForeground(java.awt.Color.black);
		width5.setFont(new Font("Dialog", Font.BOLD, 12));
		width5.setBounds(12,108,144,24);
		closeButton.setText("close");
		closeButton.setActionCommand("close");
		getContentPane().add(closeButton);
		closeButton.setBackground(new java.awt.Color(204,204,204));
		closeButton.setForeground(java.awt.Color.black);
		closeButton.setFont(new Font("Dialog", Font.BOLD, 12));
		closeButton.setBounds(12,144,144,24);
		//}}

		//{{INIT_MENUS
		//}}
	
		//{{REGISTER_LISTENERS
		SymAction lSymAction = new SymAction();
		width1.addActionListener(lSymAction);
		width2.addActionListener(lSymAction);
		width3.addActionListener(lSymAction);
		width4.addActionListener(lSymAction);
		width5.addActionListener(lSymAction);
		closeButton.addActionListener(lSymAction);
		//}}
		
		buttons=new Vector();
		buttons.addElement(width1);
		buttons.addElement(width2);
		buttons.addElement(width3);
		buttons.addElement(width4);
		buttons.addElement(width5);
		buttons.addElement(this.closeButton);
		
		int numberOfButtons=buttons.size();
		for(int i=0;i<numberOfButtons;i++){
		    ControlledButton b=(ControlledButton)(buttons.elementAt(i));
		    b.setID(i);
		    b.setFrame(this);
		}
	}

	public WidthSelectFrame(String sTitle)
	{
		this();
		setTitle(sTitle);
	}

	public void setVisible(boolean b)
	{
		if (b)
			setLocation(50, 50);
		super.setVisible(b);
	}

	static public void main(String args[])
	{
		(new WidthSelectFrame()).setVisible(true);
	}

	public void addNotify()
	{
		// Record the size of the window prior to calling parents addNotify.
		Dimension size = getSize();

		super.addNotify();

		if (frameSizeAdjusted)
			return;
		frameSizeAdjusted = true;

		// Adjust size of frame according to the insets and menu bar
		Insets insets = getInsets();
		javax.swing.JMenuBar menuBar = getRootPane().getJMenuBar();
		int menuBarHeight = 0;
		if (menuBar != null)
			menuBarHeight = menuBar.getPreferredSize().height;
		setSize(insets.left + insets.right + size.width, insets.top + insets.bottom + size.height + menuBarHeight);
	}

	// Used by addNotify
	boolean frameSizeAdjusted = false;

	//{{DECLARE_CONTROLS
	controlledparts.ControlledButton width1 = new controlledparts.ControlledButton();
	controlledparts.ControlledButton width2 = new controlledparts.ControlledButton();
	controlledparts.ControlledButton width3 = new controlledparts.ControlledButton();
	controlledparts.ControlledButton width4 = new controlledparts.ControlledButton();
	controlledparts.ControlledButton width5 = new controlledparts.ControlledButton();
	controlledparts.ControlledButton closeButton = new controlledparts.ControlledButton();
	//}}

	//{{DECLARE_MENUS
	//}}


	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == width1)
				width1_actionPerformed(event);
			else if (object == width2)
				width2_actionPerformed(event);
			else if (object == width3)
				width3_actionPerformed(event);
			else if (object == width4)
				width4_actionPerformed(event);
			else if (object == width5)
				width5_actionPerformed(event);
			else if (object == closeButton)
				closeButton_actionPerformed(event);
			
		}
	}

	void width1_actionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		width1_actionPerformed_Interaction1(event);
	}

	void width1_actionPerformed_Interaction1(java.awt.event.ActionEvent event)
	{
		try {
//			width1.show();
		} catch (Exception e) {
		}
		/*
		this.setWidth(width1);
		*/
	}

	void width2_actionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		width2_actionPerformed_Interaction1(event);
	}

	void width2_actionPerformed_Interaction1(java.awt.event.ActionEvent event)
	{
		try {
	//		width2.show();
		} catch (Exception e) {
		}
		/*
		setWidth(width2);
		*/
	}

	void width3_actionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		width3_actionPerformed_Interaction1(event);
	}

	void width3_actionPerformed_Interaction1(java.awt.event.ActionEvent event)
	{
		try {
//			width3.show();
		} catch (Exception e) {
		}
		/*
		setWidth(width3);
		*/
	}

	void width4_actionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		width4_actionPerformed_Interaction1(event);
	}

	void width4_actionPerformed_Interaction1(java.awt.event.ActionEvent event)
	{
		try {
//			width4.show();
		} catch (Exception e) {
		}
		/*
		setWidth(width4);
		*/
	}

	void width5_actionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		width5_actionPerformed_Interaction1(event);
	}

	void width5_actionPerformed_Interaction1(java.awt.event.ActionEvent event)
	{
		try {
//			width5.show();
		} catch (Exception e) {
		}
		/*
		setWidth(width5);
		*/
	}


	void closeButton_actionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		closeButton_actionPerformed_Interaction1(event);
	}

	void closeButton_actionPerformed_Interaction1(java.awt.event.ActionEvent event)
	{
		try {
//			closeButton.show();
		} catch (java.lang.Exception e) {
		}
	}
}